### ISSUE TITLE
JS emergency compliment

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/compliment-express#55]
https://github.com/jschultz21/emergency-compliment

can't for the life of me figure out how to get this deployed on heroku. Tried using MongoLab but the db still doesn't seem to be connecting on the deployed version: https://rg-feminist-generator.herokuapp.com/. 

complete: 5
comfort: 4

**Comment by nolds9** [comment]
👍 does the deploy error persist? Seems to be working for me

**Comment by jschultz21** [comment]
I finally got it!!! https://rg-feminist-generator.herokuapp.com/ I think
the error had something to do with the body parser being .json vs.
.urlencoded...
