### ISSUE TITLE
Emergency compliment HW (Michael Holzheimer)

### ISSUE THREAD

**Issue by alpha2262** [ga-wdi-exercises/compliment-express#57]
Actual repo for content: https://github.com/alpha2262/compliments/tree/michael

One semi-related question, I can't seem to disconnect from the wrong repo then reconnect to this one. My steps were:
1. git remote rm compliments
  returned: fatal: No such remote: compliments
2. git remote add origin <link to my forked compliments express file>
  returned: fatal: remote origin already exists.

Completeness: 2
Comfort: 2

**Comment by jshawl** [comment]
you should

```
git remote rm origin
git remote add origin the correct url
```

👍
