### ISSUE TITLE
Christopher Homework

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/compliment-express#85]
https://github.com/chris-A-phillips/emergency-compliment

Completness: 4
Comfort: 5

I've built this a couple times now and have started to use the express command line interface in order to generate a skeleton app for my projects. It's also helped me get a lot more familiar with what an 'express in the wild' might look like.

Notes: jade vs handlebars is just a preference thing, but I can see where one or the other can solve problems the other can't. I've worked this problem with both and still have not decided.

I like how lean express is. 

module.exports for custom functions is great, but I don't know if labeling them as controllers is syntactically correct. Building your own custom modules that do awesome stuff is great, but are they really controllers? More code reviews and experience will help answer this.

Level 2 was pretty easy, but I've been trying to see if there are solutions for doing level 3 without a db. We learned how to persist data locally, but that doesn't help sharing compliment lists. Will research more and try to tackle it when I have more time.

Sorry for being so late on this one! I'm trying to tackle MEAN at my own pace to make sure I understand everything as fully as possible. I'm not sure if this pace is slower this time around since we're at week 9 and have learned so much already, but it's less of a feeling of being overwhelmed or anything and more a feeling of stopping to smell the air a bit. 

Solution branches, and rushing to finish for the sake of finishing be damned this time around. 

Sometimes it feels like we only get a brief stint with some of these concepts and I want to take as much time as I feel like I need to actually understand some of this.

**Comment by nayana487** [comment]
👍
